openapi: '3.0.0'
info:
  title: API - Vagas
  description: Documentação de rotas do API
  version: 1.0.0 BETA
servers:
  - url: /
    description: API - Vagas
schemes:
  - http

paths:
  /health-check:
    get:
      tags:
        - Health check
      summary: Consultar status da API
      responses:
        200:
          description: OK

  /vagas:
    get:
      tags:
        - Vagas
      summary: Buscar todas as vagas disponíveis
      responses:
        200:
          description: busca realizada com sucesso
          content:
            application/json:
              schema:
                type: object
                example: { 'count': 0, 'rows': [] }

    post:
      tags:
        - Vagas
      summary: Registro de vagas
      parameters:
        - in: header
          name: x-access-token
          schema:
            type: string
          required: true

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                title:
                  type: string
                type:
                  type: string
                site:
                  type: string
                workload:
                  type: number
                  format: double
                salary:
                  type: number
                  format: double
                scholarity:
                  type: string
                startingDate:
                  type: string
                  format: date
                endingDate:
                  type: string
                  format: date
                userId:
                  type: integer

      responses:
        '201':
          description: vaga criada com sucesso

  /vagas/{id}:
    get:
      tags:
        - Vagas
      summary: Buscar vaga por identificador
      parameters:
        - in: path
          name: id
          description: User ID
          required: true
          schema:
            type: integer
            format: int64

        - in: header
          name: x-access-token
          schema:
            type: string
          required: true
      responses:
        200:
          description: busca realizada com sucesso

    put:
      tags:
        - Vagas
      summary: Atualização de vagas
      parameters:
        - in: path
          name: id
          description: User ID
          required: true
          schema:
            type: integer
            format: int64

        - in: header
          name: x-access-token
          schema:
            type: string
          required: true
      responses:
        200:
          description: vaga atualizada com sucesso

    delete:
      tags:
        - Vagas
      summary: Deleção de vagas
      parameters:
        - in: path
          name: id
          description: User ID
          required: true
          schema:
            type: integer
            format: int64

        - in: header
          name: x-access-token
          schema:
            type: string
          required: true
      responses:
        204:
          description: vaga excluída com sucesso

  /vagas/aplicacao:
    post:
      tags:
        - Vagas
      summary: Aplicação de vagas
      parameters:
        - in: path
          name: id
          description: User ID
          required: true
          schema:
            type: integer
            format: int64

        - in: header
          name: x-access-token
          schema:
            type: string
          required: true

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jobId:
                  type: integer
                  format: int64
      responses:
        200:
          description: operação realizada com sucesso

  /usuarios:
    post:
      tags:
        - Usuários
      summary: Cadastro de usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string

      responses:
        '201':
          description: conta criada com sucesso
